services:
  app:
    build: .
    container_name: hyperbrain
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hyperbrain
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: "./"
          target: "/usr/src/app"
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyperbrain
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
