FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY ./package.json .
COPY ./pnpm-lock.yaml .
COPY ./pnpm-workspace.yaml .
COPY ./tsconfig.json .
COPY ./turbo.json .

COPY ./packages/ ./packages/

COPY ./apps/web/package.json ./apps/web/
COPY ./apps/web/tailwind.config.ts ./apps/web/
COPY ./apps/web/eslint.config.js ./apps/web/
COPY ./apps/web/postcss.config.mjs ./apps/web/

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev:docker"]
