name: Lint
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install pnpm
        uses: pnpm/actions-setup@v2
        with:
          version: 9

      - name: install dependencies
        uses: pnpm install

      - name: Run Eslint
        uses: pnpm lint
